#!/bin/bash

# Where to redirect build messages
BUILD_OUTPUT="/dev/null"
#BUILD_OUTPUT=/dev/stdout

PACKAGE_DIR="/home/jmata/CS605/Monte-Carlo-Pi-Approximation/Monte-Carlo-Pi-Approximation"

SRC_DIR="$PACKAGE_DIR/src"
BUILD_DIR="$PACKAGE_DIR/build"
DATA_FILES="$PACKAGE_DIR/data"
PLOT_FILES="$PACKAGE_DIR/plotting"
EXE="MonteCarloApproximation"


echo "*******************************************" > $BUILD_OUTPUT
echo "          Recompiling files                " > $BUILD_OUTPUT
echo "*******************************************" > $BUILD_OUTPUT
make -C $SRC_DIR > $BUILD_OUTPUT

NUM_THREADS=(1 2 4 8 16 32 64 128 256 512)
for thread_num in ${NUM_THREADS[@]}
do
    
    NUM_POINTS=(1000 10000 100000 1000000 10000000 100000000)
    for points in ${NUM_POINTS[@]}
    do
        $BUILD_DIR/$EXE -n $thread_num -p $points
    done

done